
services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker=true" # Enable Docker provider
      - "--entrypoints.web.address=:80" # Define HTTP entrypoint
      - "--entrypoints.websecure.address=:443" # Define HTTPS entrypoint
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=aaron+letsencrypt@lo-res.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    # command:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Access Docker socket
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  utranslator:
    #build: .
    image: utranslator:0.1
    container_name: utranslator
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`utranslator.lo-res.org`)" # Replace with your domain
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port="9948"
    env_file:
      - .env
    ports:
      - "9948:9948"
    networks:
      - web
    depends_on:
      - traefik

networks:
  web:
    name: web
    driver: external
