
services:
  # traefik:
  #   image: traefik:v3.1
  #   command:
  #     - "--providers.docker=true" # Enable Docker provider
  #     - "--entrypoints.web.address=:80" # Define HTTP entrypoint
  #     - "--entrypoints.websecure.address=:443" # Define HTTPS entrypoint
  #     - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
  #     - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
  #     - "--certificatesresolvers.myresolver.acme.email=aaron+letsencrypt@lo-res.org"
  #     - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  #   ports:
  #     - "80:80"     # HTTP
  #     - "443:443"   # HTTPS
  #   # command:
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro" # Access Docker socket
  #     - "./letsencrypt:/letsencrypt"
  #   networks:
  #     - web

  utranslator:
    image: utranslator:0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION="0.1"
    environment:
      PYTHONPATH: /app
    env_file: 
      - ".env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.utranslator.rule=Host(`utranslator.lo-res.org`)"
      - "traefik.http.routers.utranslator.entrypoints=websecure"
      - "traefik.http.routers.utranslator.tls.certresolver=myresolver"
      - "traefik.http.services.utranslator.loadbalancer.server.port=9948"
    ports:
      - "9948:9948"
    networks:
      - web

networks:
  web:
    external: true

